FLATS_COLS = {
    "Numer oferty": "offerId",
    "Numer oferty pożądany": "offerIdExpected",
    "Typ oferty": "offerType",
    "Status": "offerStatus",
    "Data dodania": "dateAdded",
    "Data zmiany": "dateChanged",
    "Data aktualizacji": "dateUpdated",
    "Data zamknięcia transakcji": "dateEndTransaction",
    "Lokalizacja": "localization",
    "Ulica": "street",
    "Stan prawny": "lawStatus",
    "SWO ID": "skipOffer",
    "Cena": "price",
    "Cena ofertowa": "priceOffer",
    "Cena transakcyjna": "priceSold",
    "Powierzchnia": "livingArea",
    "Balkon": "balcony",
    "Rynek": "market",
    "Cena za m2": "priceM2",
    "Czynsz administracyjny": "rent",
    "Materiał": "material",
    "Stan mieszkania": "flatQuality",
    "Cena z miejscami parkingowymi": "price_with_parking",
    "Cena z wszelkimi dodatkami": "price_with_addings",
    "Piętro": "floor",
    "Ogród": "garden",
    "Liczba pięter": "floorsNumber",
    "Winda": "elevator",
    "Garaż/Miejsca parkingowe": "parkingPlace",
    "Rodzaj budynku": "buildingType",
    "Rok budowy": "yearBuilt",
    "Stan budynku": "buildingQuality",
    "Ochrona": "security",
    "Teren strzeżony": "guardedArea",
    "Monitoring": "monitoring",
    "Kontrola dostępu": "securityControl",
    "Liczba pokoi": "roomsNumber",
    "Typ kuchni": "kitchenType",
    "Piwnica": "basement",
    "Liczba balkonów": "balconyQuantity",
    "Opis": "description",
    "Uwagi": "comments",
    "Osiedle strzeżone": "guardedEstate",
    "Recepcja": "reception",
    "Liczba loggi": "loggiasQuantity",
    "Komórka": "storageRoom",
    "Poddasze użytkowe": "attic",
    "Liczba tarasów": "terracesQuantity",
    "Liczba balkonów francuskich": "frenchBalconyQuantity",
    "Numer zewnętrzny": "outside_no",
    "Cena za parking podziemny (miejsce)": "priceParkingUnderground",
    "Cena za parking naziemny (miejsce)": "priceParkingGround",
    "Uwagi dla użytkowników z SWO/MLS": "swo_comment",
    "balkon": "balconyDesc",
    "francu": "frenchBalconyDesc",
    "taras": "terraceDesc",
    "wind": "elevatorDesc",
    "piwnic": "basementDesc",
    "komórk": "storageroomDesc",
    "strych": "atticDesc",
    "gospodarcze": "utilityroomDesc",
    "postojow": "parkingSpaceDesc",
    "parking": "parkingPlaceDesc",
    "przynależn": "belongingDesc",
    "garaż": "garageDesc",
    "możliwość": "possibilityDesc",
    "ogród": "gardenDesc",
    "ogrod": "gardenDesc2",
    "działka": "gardenDesc3",
    "ocieplony": "insulatedBuildingDesc",
    "moderniz": "modernizatedBuildingDesc",
    "odrestaur": "restoredBuildingDesc",
    "odnow": "renewedBuildingDesc",
    "ociepl": "insulatedBuildingDesc2",
    "remon": "renovationDesc",
    "elewac": "elevationDesc",
    "dozór": "supervisionDesc",
    "dozor": "supervisionDesc2",
    "monitoring": "monitoringDesc",
    "monit": "monitoringDesc2",
    "ochron": "securityDesc",
    "alarm": "alarmDesc",
    "strzeż": "guardedDesc",
    "portier": "doorkeeperDesc",
    "wspólnot": "communityFlatDesc",
    "spółdziel": "cooperativeflatDesc",
    "kuchni": "kitchenDesc",
    "aneks": "kitchenAnnexDesc",
    "widna": "kitchenBrightDesc",
    "ciemna": "kitchenDarkDesc",
    "prześwit": "kitchenClearanceDesc",
    "z oknem": "kitchenWindowDesc",
    "z jadalni": "kitchenDiningRoomDesc",
    "oficyn": "outbuildingDesc",
    "linia": "outbuildingDesc2",
    "linii": "outbuildingDesc3",
    "opłat": "feesDesc",
    "bezczynsz": "withoutRentDesc",
    "czynsz": "rentDesc",
    "poziom": "levelDesc",
    "ul.": "ul1",
    "al.": "al1",
    " zł": "zl1",
    " zl": "zl2",
    "pln": "zl3",
    "ul\.": "ul2",
    "al\.": "al2",
    'technology_ans': 'technology_ans',
    'balcony_ans': 'balcony_ans',
    'law_status_ans': 'law_status_ans',
    'elevator_ans': 'elevator_ans',
    'basement_ans': 'basement_ans',
    'garage_ans': 'garage_ans',
    'garden_ans': 'garden_ans',
    'modernization_ans': 'modernization_ans',
    'alarm_ans': 'alarm_ans',
    'kitchen_ans': 'kitchen_ans',
    'outbuilding_ans': 'outbuilding_ans',
    'rent_ans': 'rent_ans',
    'comments_ans': 'comments_ans',
    'quality_ans': 'quality_ans',
    'delete_ans': 'delete_ans',
    'status': 'status',
    'user_in': 'user_in',
    'update_date': 'update_date',

}

# FLATS_COLS_TO_GET = ['offerId', 'offerIdExpected', 'offerType', 'offerStatus', 'dateAdded', 'dateChanged',
#                      'dateUpdated',
#                      'dateEndTransaction', 'localization', 'street', 'lawStatus', 'price',
#                      'priceOffer', 'priceSold',
#                      'livingArea', 'balcony', 'market', 'priceM2', 'rent', 'material', 'flatQuality',
#                      'floor', 'garden', 'floorsNumber', 'elevator', 'parkingPlace', 'buildingType',
#                      'yearBuilt', 'buildingQuality', 'security', 'guardedArea',
#                      'monitoring', 'securityControl', 'roomsNumber', 'kitchenType', 'basement',
#                      'balconyQuantity', 'description', 'balconyQuantity', 'description', 'guardedEstate',
#                      'loggiasQuantity', 'storageRoom', 'attic', 'terracesQuantity', 'frenchBalconyQuantity',
#                      'priceParkingUnderground', 'priceParkingGround',
#                      'balconyDesc', 'frenchBalconyDesc', 'terraceDesc', 'elevatorDesc', 'basementDesc',
#                      'storageroomDesc', 'atticDesc', 'utilityroomDesc', 'parkingSpaceDesc',
#                      'parkingPlaceDesc', 'belongingDesc', 'garageDesc', 'possibilityDesc',
#                      'gardenDesc', 'gardenDesc2', 'gardenDesc3', 'insulatedBuildingDesc',
#                      'modernizatedBuildingDesc', 'restoredBuildingDesc', 'renewedBuildingDesc',
#                      'insulatedBuildingDesc2', 'renovationDesc', 'elevationDesc', 'supervisionDesc',
#                      'supervisionDesc2', 'monitoringDesc', 'monitoringDesc2', 'securityDesc', 'alarmDesc',
#                      'guardedDesc', 'doorkeeperDesc', 'communityFlatDesc', 'cooperativeflatDesc',
#                      'kitchenDesc', 'kitchenAnnexDesc', 'kitchenBrightDesc', 'kitchenDarkDesc',
#                      'kitchenClearanceDesc', 'kitchenWindowDesc', 'kitchenDiningRoomDesc', 'outbuildingDesc',
#                      'outbuildingDesc2', 'outbuildingDesc3', 'feesDesc', 'withoutRentDesc', 'rentDesc',
#                      'levelDesc']

HOUSES_COLS = {
    "Numer oferty": "offerId",
    "Numer oferty pożądany": "offerIdExpected",
    "Typ oferty": "offerType",
    "Status": "offerStatus",
    "Data dodania": "dateAdded",
    "Data zmiany": "dateChanged",
    "Data aktualizacji": "dateUpdated",
    "Lokalizacja": "localization",
    "Ulica": "street",
    "Stan prawny": "lawStatus",
    "Stan prawny gruntu": "law_status_plot",
    "SWO ID": "swo_id",
    "Cena": "price",
    "Powierzchnia użytkowa": "livingArea",
    "Powierzchnia": "houseArea",
    "Powierzchnia działki": "plotArea",
    "Stan nieruchomości": "houseQuality",
    "Cena za m2": "priceM2",
    "Rynek": "market",
    "Typ domu": "houseType",
    "Stan budynku": "buildingQuality",
    "Materiał": "material",
    "Rok budowy": "yearBuilt",
    "Garaż/Miejsca parkingowe": "garage_or_parking",
    "Liczba pięter": "floorsNumber",
    "Garaż (liczba miejsc)": "garagesNumber",
    "Liczba pokoi": "roomsNumber",
    "Typ kuchni": "kitchenType",
    "Liczba łazienek": "bathsNumber",
    "Piwnica": "basement",
    "Opis": "description",
    "Uwagi": "comments",
    "Kształt działki": "lotShape",
    "Ogród": "garden",
    "Ochrona": "security",
    "Teren ogrodzony": "fence",
    "Teren strzeżony": "guardedArea",
    "Osiedle strzeżone": "guardedEstate",
    "Monitoring": "monitoring",
    "Kontrola dostępu": "securityControl",
    "postojow": "parkingSpaceDesc",
    "parking": "parkingPlaceDesc",
    "przynależn": "belongingDesc",
    "garaż": "garageDesc",
    "możliwość": "possibilityDesc",
    "działk": "plotDesc",
    "własno": "lawStatus1aDesc",
    "spóldziel": "lawStatus2aDesc",
    "wieczyst": "lawStatus3aDesc",
    "wspólnot": "lawStatus4aDesc",
    "użytkowani": "eternal_use",
    "ocieplony": "insulatedBuildingDesc",
    "moderniz": "modernizatedBuildingDesc",
    "odrestaur": "restoredBuildingDesc",
    "odnow": "renewedBuildingDesc",
    "ociepl": "insulatedBuildingDesc2",
    "remon": "renovationDesc",
    "elewac": "elevationDesc",
    "dozór": "supervisionDesc",
    "dozor": "supervisionDesc2",
    "monitoring": "monitoringDesc",
    "monit": "monitoringDesc2",
    "ochron": "securityDesc",
    "alarm": "alarmDesc",
    "strzeż": "guardedDesc",
    "portier": "doorkeeperDesc",
    "kuchni": "kitchenDesc",
    "aneks": "kitchenAnnexDesc",
    "widna": "kitchenBrightDesc",
    "ciemna": "kitchenDarkDesc",
    "prześwit": "kitchenClearanceDesc",
    "z oknem": "kitchenWindowDesc",
    "z jadalni": "kitchenDiningRoomDesc",
    "ul.": "street1Desc",
    "al.": "street2Desc",
    "toalet": "toilets1Desc",
    "ubikac": "toilets2Desc",
    "łazienk": "toilets3Desc",
    "szerego": "buildingType1Desc",
    "jednorodzin": "buildingType2Desc",
    "wolnostoj": "buildingType3Desc",
    "wolno": "buildingType4Desc",
    "wielorodzin": "buildingType5Desc",
    "bliźnia": "buildingType6Desc",
    "zabudow": "buildingType7Desc",
    "technology_ans": "technology_ans",
    "law_status_ans": "law_status_ans",
    'house_type_ans': 'house_type_ans',
    'garage_ans': 'garage_ans',
    'modernization_ans': 'modernization_ans',
    'alarm_ans': 'alarm_ans',
    'kitchen_ans': 'kitchen_ans',
    'bath_no_ans': 'bath_no_ans',
    'comments_ans': 'comments_ans',
    'quality_ans': 'quality_ans',
    'delete_ans': 'delete_ans',
    'status': 'status',
    'user_in': 'user_in',
    'update_date': 'update_date',
}

PLOTS_COLS = {
    "Numer oferty": "offerId",
    "Numer oferty pożądany": "offerIdExpected",
    "Typ oferty": "offerType",
    "Status": "offerStatus",
    "Data dodania": "dateAdded",
    "Data zmiany": "dateChanged",
    "Data aktualizacji": "dateUpdated",
    "Lokalizacja": "localization",
    "Ulica": "street",
    "Stan prawny gruntu": "lawStatus",
    "SWO ID": "swo_id",
    "Cena": "price",
    "Powierzchnia działki": "plotArea",
    "Cena za (m2/a/ha)": "priceM2",
    "Prąd": "electricity",
    "Woda": "water",
    "Gaz": "gas",
    "Rynek": "market",
    "Przeznaczenie działki": "plotPurpose",
    "Droga dojazdowa": "accessRoad",
    "Opis": "description",
    "Uwagi": "comments",
    "Kanalizacja": "sewers",
    "Kształt działki": "lotShape",
    "Plan miejscowy": "localPlan",
    "Przeznaczenie działki w planie lub studium": "plotPurposeInPlan",
    "Wydane warunki zabudowy": "buildingConditions",
    "Aktualne pozwolenie na budowę": "buildingPermit",
    "Ujęcie wody": "waterIntake",
    "Rodzaj kanalizacji": "sewageType",
    "Ogrodzenie": "fence",
    "Obecna zabudowa działki": "buildingOnPlot",
    "Stan prawny": "lawStatus",
    "szerego": "buildingType1Desc",
    "jednorodzin": "buildingType2Desc",
    "wolnostoj": "buildingType3Desc",
    "wolno": "buildingType4Desc",
    "wielorodzin": "buildingType5Desc",
    "bliźnia": "buildingType6Desc",
    "komerc": "commercialPlotDesc",
    "handl": "tradePlotDesc",
    "usług": "servicesPlotDesc",
    "magazyn": "warehousePlotDesc",
    "produkc": "productionPlotDesc",
    "przemysł": "industryPlotDesc",
    "inwestycyjn": "investmentPlotDesc",
    "towarzysząc": "accompanyingPlotDesc",
    "nieuciążli": "notBurdenPlotDesc",
    "prąd": "electricityDesc",
    "energia": "energyDesc",
    "elektrycz": "electricDesc",
    "ZK": "zkDesc",
    "gaz": "gasDesc",
    "woda": "waterDesc",
    "wody": "water2Desc",
    "wodociąg": "water3Desc",
    "kanaliza": "sewersDesc",
    "uzbroj": "armedDesc",
    "szambo": "septictankDesc",
    "gruntow": "accessRoad1Desc",
    "w drodze": "inRoadDesc",
    "granicy": "inBorderDesc",
    "działce": "inPlotDesc",
    "dom": "houseDesc",
    "budynek": "buildingDesc",
    "rozbiór": "dismantlingDesc",
    "utwardzon": "accessRoad2Desc",
    "asfalt": "accessRoad3Desc",
    "brukow": "accessRoad4Desc",
    "żużel": "accessRoad5Desc",
    "żużlowa": "accessRoad6Desc",
    "jumbo": "accessRoad7Desc",
    "ażuro": "accessRoad8Desc",
    "jomb": "accessRoad9Desc",
    "yomb": "accessRoad10Desc",
    "poln": "accessRoad11Desc",
    "użytkowani": "lawStatus4aDesc",
    "wieczyste": "law1Desc",
    "służebność": "law2Desc",
    "ogrodz": "fencedArea1Desc",
    "siatka": "fencedArea2Desc",
    "x": "lotShape1Desc",
    "prostokąt": "lotShape2Desc",
    "kwadrat": "lotShape3Desc",
    "trójkąt": "lotShape4Desc",
    "trapez": "lotShape5Desc",
    "podłuż": "lotShape6Desc",
    "regularny": "lotShape7Desc",
    "kształt": "lotShape8Desc",
    "zagospodarowani": "lawStatus1Desc",
    "MPZP": "lawStatus2Desc",
    "przestrzenn": "lawStatus3Desc",
    "studium": "lawStatus4Desc",
    "warunk": "lawStatus5Desc",
    "zabudow": "buildingType7Desc",
    "pozwoleni": "allowanceDesc",
    'document_ans': 'document_ans',
    'purpose_of_the_plot_ans': 'purpose_of_the_plot_ans',
    'purpose_of_the_plot_jr_ans': 'purpose_of_the_plot_jr_ans',
    'purpose_of_the_plot_wr_ans': 'purpose_of_the_plot_wr_ans',
    'purpose_of_the_plot_jwr_ans': 'purpose_of_the_plot_jwr_ans',
    'purpose_of_the_plot_fmt_ans': 'purpose_of_the_plot_fmt_ans',
    'house_type_ans': 'house_type_ans',
    'lot_shape_ans': 'lot_shape_ans',
    'building_permit_ans': 'building_permit_ans',
    'water_ans': 'water_ans',
    'electricity_ans': 'electricity_ans',
    'gas_ans': 'gas_ans',
    'sewers_ans': 'sewers_ans',
    'is_building_on_plot_ans': 'is_building_on_plot_ans',
    'access_road_ans': 'access_road_ans',
    'fence_ans': 'fence_ans',
    'comments_ans': 'comments_ans',
    'delete_ans': 'delete_ans',
    'status': 'status',
    'user_in': 'user_in',
    'update_date': 'update_date',

}
