FLATS_COLS = {
    "Numer oferty": "offerId",
    "Numer oferty pożądany": "offerIdExpected",
    "Typ oferty": "offerType",
    "Status": "offerStatus",
    "Data dodania": "dateAdded",
    "Data zmiany": "dateChanged",
    "Data aktualizacji": "dateUpdated",
    "Data zamknięcia transakcji": "dateEndTransaction",
    "Lokalizacja": "localization",
    "Ulica": "street",
    "Stan prawny": "lawStatus",
    "SWO ID": "skipOffer",
    "Cena": "price",
    "Cena ofertowa": "priceOffer",
    "Cena transakcyjna": "priceSold",
    "Powierzchnia": "livingArea",
    "Balkon": "balcony",
    "Rynek": "market",
    "Cena za m2": "priceM2",
    "Czynsz administracyjny": "rent",
    "Materiał": "material",
    "Stan mieszkania": "flatQuality",
    "Cena z miejscami parkingowymi": "price_with_parking",
    "Cena z wszelkimi dodatkami": "price_with_addings",
    "Piętro": "floor",
    "Ogród": "garden",
    "Liczba pięter": "floorsNumber",
    "Winda": "elevator",
    "Garaż/Miejsca parkingowe": "parkingPlace",
    "Rodzaj budynku": "buildingType",
    "Rok budowy": "yearBuilt",
    "Stan budynku": "buildingQuality",
    "Ochrona": "security",
    "Teren strzeżony": "guardedArea",
    "Monitoring": "monitoring",
    "Kontrola dostępu": "securityControl",
    "Liczba pokoi": "roomsNumber",
    "Typ kuchni": "kitchenType",
    "Piwnica": "basement",
    "Liczba balkonów": "balconyQuantity",
    "Opis": "description",
    "Uwagi": "comments",
    "Osiedle strzeżone": "guardedEstate",
    "Recepcja": "reception",
    "Liczba loggi": "loggiasQuantity",
    "Komórka": "storageRoom",
    "Poddasze użytkowe": "attic",
    "Liczba tarasów": "terracesQuantity",
    "Liczba balkonów francuskich": "frenchBalconyQuantity",
    "Numer zewnętrzny": "outside_no",
    "Cena za parking podziemny (miejsce)": "priceParkingUnderground",
    "Cena za parking naziemny (miejsce)": "priceParkingGround",
    "Uwagi dla użytkowników z SWO/MLS": "swo_comment",
    "balkon": "balconyDesc",
    "francu": "frenchBalconyDesc",
    "taras": "terraceDesc",
    "wind": "elevatorDesc",
    "piwnic": "basementDesc",
    "komórk": "storageroomDesc",
    "strych": "atticDesc",
    "gospodarcze": "utilityroomDesc",
    "postojow": "parkingSpaceDesc",
    "parking": "parkingPlaceDesc",
    "przynależn": "belongingDesc",
    "garaż": "garageDesc",
    "możliwość": "possibilityDesc",
    "ogród": "gardenDesc",
    "ogrod": "gardenDesc2",
    "działka": "gardenDesc3",
    "ocieplony": "insulatedBuildingDesc",
    "moderniz": "modernizatedBuildingDesc",
    "odrestaur": "restoredBuildingDesc",
    "odnow": "renewedBuildingDesc",
    "ociepl": "insulatedBuildingDesc2",
    "remon": "renovationDesc",
    "elewac": "elevationDesc",
    "dozór": "supervisionDesc",
    "dozor": "supervisionDesc2",
    "monitoring": "monitoringDesc",
    "monit": "monitoringDesc2",
    "ochron": "securityDesc",
    "alarm": "alarmDesc",
    "strzeż": "guardedDesc",
    "portier": "doorkeeperDesc",
    "wspólnot": "communityFlatDesc",
    "spółdziel": "cooperativeflatDesc",
    "kuchni": "kitchenDesc",
    "aneks": "kitchenAnnexDesc",
    "widna": "kitchenBrightDesc",
    "ciemna": "kitchenDarkDesc",
    "prześwit": "kitchenClearanceDesc",
    "z oknem": "kitchenWindowDesc",
    "z jadalni": "kitchenDiningRoomDesc",
    "oficyn": "outbuildingDesc",
    "linia": "outbuildingDesc2",
    "linii": "outbuildingDesc3",
    "opłat": "feesDesc",
    "bezczynsz": "withoutRentDesc",
    "czynsz": "rentDesc",
    "poziom": "levelDesc",
    "ul.": "ul1",
    "al.": "al1",
    " zł": "zl1",
    " zl": "zl2",
    "pln": "zl3",
    "ul\.": "ul2",
    "al\.": "al2",
    "status": "new",
}

FLATS_COLS_TO_GET = ['offerId', 'offerIdExpected', 'offerType', 'offerStatus', 'dateAdded', 'dateChanged',
                     'dateUpdated',
                     'dateEndTransaction', 'localization', 'street', 'lawStatus', 'price',
                     'priceOffer', 'priceSold',
                     'livingArea', 'balcony', 'market', 'priceM2', 'rent', 'material', 'flatQuality',
                     'floor', 'garden', 'floorsNumber', 'elevator', 'parkingPlace', 'buildingType',
                     'yearBuilt', 'buildingQuality', 'security', 'guardedArea',
                     'monitoring', 'securityControl', 'roomsNumber', 'kitchenType', 'basement',
                     'balconyQuantity', 'description', 'balconyQuantity', 'description', 'guardedEstate',
                     'loggiasQuantity', 'storageRoom', 'attic', 'terracesQuantity', 'frenchBalconyQuantity',
                     'priceParkingUnderground', 'priceParkingGround',
                     'balconyDesc', 'frenchBalconyDesc', 'terraceDesc', 'elevatorDesc', 'basementDesc',
                     'storageroomDesc', 'atticDesc', 'utilityroomDesc', 'parkingSpaceDesc',
                     'parkingPlaceDesc', 'belongingDesc', 'garageDesc', 'possibilityDesc',
                     'gardenDesc', 'gardenDesc2', 'gardenDesc3', 'insulatedBuildingDesc',
                     'modernizatedBuildingDesc', 'restoredBuildingDesc', 'renewedBuildingDesc',
                     'insulatedBuildingDesc2', 'renovationDesc', 'elevationDesc', 'supervisionDesc',
                     'supervisionDesc2', 'monitoringDesc', 'monitoringDesc2', 'securityDesc', 'alarmDesc',
                     'guardedDesc', 'doorkeeperDesc', 'communityFlatDesc', 'cooperativeflatDesc',
                     'kitchenDesc', 'kitchenAnnexDesc', 'kitchenBrightDesc', 'kitchenDarkDesc',
                     'kitchenClearanceDesc', 'kitchenWindowDesc', 'kitchenDiningRoomDesc', 'outbuildingDesc',
                     'outbuildingDesc2', 'outbuildingDesc3', 'feesDesc', 'withoutRentDesc', 'rentDesc',
                     'levelDesc']

HOUSES_COLS = {
    "Numer oferty": "offerId",
    "Numer oferty pożądany": "offerIdExpected",
    "Typ oferty": "offerType",
    "Status": "offerStatus",
    "Data dodania": "dateAdded",
    "Data zmiany": "dateChanged",
    "Data aktualizacji": "dateUpdated",
    "Lokalizacja": "localization",
    "Ulica": "street",
    "Stan prawny": "lawStatus",
    "Stan prawny gruntu": "lawStatus",
    "SWO ID": "swo_id",
    "Cena": "price",
    "Powierzchnia użytkowa": "livingArea",
    "Powierzchnia": "houseArea",
    "Powierzchnia działki": "plotArea",
    "Stan nieruchomości": "houseQuality",
    "Cena za m2": "priceM2",
    "Rynek": "market",
    "Typ domu": "houseType",
    "Stan budynku": "buildingQuality",
    "Materiał": "material",
    "Rok budowy": "yearBuilt",
    "Garaż/Miejsca parkingowe": "garage_or_parking",
    "Liczba pięter": "floorsNumber",
    "Garaż (liczba miejsc)": "garagesNumber",
    "Liczba pokoi": "roomsNumber",
    "Typ kuchni": "kitchenType",
    "Liczba łazienek": "bathsNumber",
    "Piwnica": "basement",
    "Opis": "description",
    "Uwagi": "comments",
    "Kształt działki": "lotShape",
    "Ogród": "garden",
    "Ochrona": "security",
    "Teren ogrodzony": "fence",
    "Teren strzeżony": "guardedArea",
    "Osiedle strzeżone": "guardedEstate",
    "Monitoring": "monitoring",
    "Kontrola dostępu": "securityControl",
    "postojow": "parkingSpaceDesc",
    "parking": "parkingPlaceDesc",
    "przynależn": "belongingDesc",
    "garaż": "garageDesc",
    "możliwość": "possibilityDesc",
    "działk": "plotDesc",
    "własno": "lawStatus1aDesc",
    "spóldziel": "lawStatus2aDesc",
    "wieczyst": "lawStatus3aDesc",
    "wspólnot": "lawStatus4aDesc",
    "użytkowani": "eternal_use",
    "ocieplony": "insulatedBuildingDesc",
    "moderniz": "modernizatedBuildingDesc",
    "odrestaur": "restoredBuildingDesc",
    "odnow": "renewedBuildingDesc",
    "ociepl": "insulatedBuildingDesc2",
    "remon": "renovationDesc",
    "elewac": "elevationDesc",
    "dozór": "supervisionDesc",
    "dozor": "supervisionDesc2",
    "monitoring": "monitoringDesc",
    "monit": "monitoringDesc2",
    "ochron": "securityDesc",
    "alarm": "alarmDesc",
    "strzeż": "guardedDesc",
    "portier": "doorkeeperDesc",
    "kuchni": "kitchenDesc",
    "aneks": "kitchenAnnexDesc",
    "widna": "kitchenBrightDesc",
    "ciemna": "kitchenDarkDesc",
    "prześwit": "kitchenClearanceDesc",
    "z oknem": "kitchenWindowDesc",
    "z jadalni": "kitchenDiningRoomDesc",
    "ul.": "street1Desc",
    "al.": "street2Desc",
    "toalet": "toilets1Desc",
    "ubikac": "toilets2Desc",
    "łazienk": "toilets3Desc",
    "szerego": "buildingType1Desc",
    "jednorodzin": "buildingType2Desc",
    "wolnostoj": "buildingType3Desc",
    "wolno": "buildingType4Desc",
    "wielorodzin": "buildingType5Desc",
    "bliźnia": "buildingType6Desc",
    "zabudow": "buildingType7Desc"
}

HOUSES_COLS_TO_GET = [
    'offerId', 'offerIdExpected', 'offerType', 'offerStatus', 'dateAdded', 'dateChanged',
    'dateUpdated', 'dateEndTransaction', 'localization', 'street', 'lawStatus', 'price',
    'priceSold', 'livingArea', 'houseArea', 'plotArea', 'houseQuality', 'priceM2',
    'houseType', 'buildingQuality', 'material', 'yearBuilt', 'parkingPlace', 'floorsNumber',
    'garagesNumber', 'roomsNumber', 'kitchenType', 'bathsNumber', 'basement',
    'lotShape', 'garden', 'fence', 'monitoring', 'security', 'guardedArea', 'guardedEstate',
    'securityControl', 'description', 'parkingSpaceDesc', 'parkingPlaceDesc', 'garageDesc',
    'belongingDesc', 'possibilityDesc', 'plotDesc', 'lawStatus1aDesc', 'lawStatus2aDesc',
    'lawStatus3aDesc', 'lawStatus4aDesc', 'insulatedBuildingDesc', 'insulatedBuildingDesc2',
    'modernizatedBuildingDesc', 'restoredBuildingDesc', 'renewedBuildingDesc', 'renovationDesc',
    'elevationDesc', 'supervisionDesc', 'supervisionDesc2', 'monitoringDesc',
    'monitoringDesc2', 'securityDesc', 'alarmDesc', 'guardedDesc', 'doorkeeperDesc', 'kitchenDesc',
    'kitchenAnnexDesc', 'kitchenBrightDesc', 'kitchenDarkDesc', 'kitchenClearanceDesc', 'kitchenWindowDesc',
    'kitchenDiningRoomDesc', 'street1Desc', 'street2Desc', 'toilets1Desc',
    'toilets2Desc', 'toilets3Desc', 'buildingType1Desc', 'buildingType2Desc', 'buildingType3Desc', 'buildingType4Desc',
    'buildingType5Desc', 'buildingType6Desc', 'buildingType7Desc']
